### ISSUE TITLE
`pack buildpack package` fails with unclear error message when missing version

### ISSUE THREAD

**Issue by matthewrobertson** [buildpacks/pack#1384]
### Summary
I am working bundling our individual buildpacks as meta-buildpacks and I forgot to include the `version` of buildpacks in my `order.groups`. This was a mistake on my part, but the error message from pack was not very helpful: 

```
ERROR: buildpack X references buildpack Y which is not present
```

There was no indication of the actual issue, which made it very difficult for me to track down.

##### Steps

1. Clone the [buildpack/samples](https://github.com/buildpacks/samples/) repo
2. Delete the `version` line in the `samples/hello-world`  `order.group` [here](https://github.com/buildpacks/samples/blob/main/buildpacks/hello-universe/buildpack.toml#L15)
3. Run `pack buildpack package my-buildpack --config ./package.toml`

##### Current behavior
The command fails with an error message like:

```
ERROR: buildpack samples/hello-universe@0.0.1 references buildpack samples/hello-world which is not present
```

##### Expected behavior

The error message should specifically indicate that the missing version is caused the failure

##### pack info

```
pack report
Pack:
  Version:  0.23.0+git-0db2c77.build-3056
  OS/Arch:  linux/amd64

Default Lifecycle Version:  0.13.1

Supported Platform APIs:  0.3, 0.4, 0.5, 0.6, 0.7, 0.8

Config:
  default-builder-image = "[REDACTED]"

  [[trusted-builders]]
    name = "[REDACTED]"
```

**Comment by imnitishng** [comment]
I'd like to work on this, I have a couple of solutions in mind please let me know which one to sounds the best -

- Replace the error message with a more verbose one, `buildpack %s references buildpack %s which does not exist in order group, please check buildpack id/version`
- Add a check that throws relevant error when the buildpack's fullname do not match (the check seems quite redundant to me)
- `BuildpackInfo.FullName()` always returns the name, even if the `version` does not exist, so we could add a new method that resolves the fullname from order group and throws an error whenever the `required` fields do not exist in the `buildpack.toml` file. This makes sense since the [documentation](https://buildpacks.io/docs/reference/spec/buildpack-api/#buildpacktoml) mentions both `id, version` to be **required**, so ideally the name should not resolve successfully in case of a missing parameter.

**Comment by jromero** [comment]
The last option seems ideal _but_ only when discussing areas that require that information such as in this case.

We do have areas where the version is optional and we resolve it for the user. For example, `pack build my-app -b my/buildpack` should work.

I do wonder if auto resolution would also be possible and a nice added feature for this use case. (We can punt that for now).

**Comment by matthewrobertson** [comment]
FWIW I don't think version should be required in the order group of a buildpack.toml. This is inconsistent with builder.toml: https://buildpacks.io/docs/reference/config/builder-config/#order-_list-required_
