### ISSUE TITLE
Docker Image Digest's Don't match on Docker Hub for "latest" and the version number tag for pack

### ISSUE THREAD

**Issue by joshuawhite929** [buildpacks/pack#1446]
### Summary
Looking at the pack Docker image located here:  https://hub.docker.com/r/buildpacksio/pack/tags and the 0.26.0 release tag as an example, the "latest" tag and "0.26.0" tags don't have the same digest.  As this is the same image, the digest should be the same.

tag: latest... sha256:5ed9488c133a85a662758907fb2d9a526800ee73bb613063ce811805a4b4316f
tag: 0.26.0... sha256:7839ad762b3be73cb50f397aed2101fc971a94efc819caa0f4c5e0b8100ba61a

### Reproduction
Look at the digests on docker hub here for each of the tags.  Note, at the time this bug was created, "latest" and "0.26.0" should be the same.

##### Current behavior
The images digests on dockerhub don't match for the same image (example "latest" and "0.26.0"

##### Expected behavior
The images digest should be the same for both images

**Comment by jromero** [comment]
@dfreilich looking at the delivery pipeline, I can assume that it's because we don't publish via the same mechanism for both tags. [One is done via buildpacks and the other via a `docker pull && docker tag && docker push`](https://github.com/buildpacks/pack/blob/98698c4a3b3dfeb511ae8b6936ea245aa1ac3b20/.github/workflows/delivery-docker.yml#L62-L73) which honestly, I'm surprised that only the manifest digest is different.

Can the github action be update to support multiple tags?

Alternatively we can switch over to https://github.com/buildpacks/github-actions#setup-pack-cli-action so that we can execute pack with the necessary flags directly.

**Comment by imjasonh** [comment]
Would you accept a PR that uses `crane cp` and [setup-crane](https://github.com/imjasonh/setup-crane) to move the image around, instead of `docker pull && tag && push`? If so I can send that shortly.

**Comment by natalieparellano** [comment]
@hone @dfreilich any thoughts here?

**Comment by natalieparellano** [comment]
Closed in 0ad7c0a42d5037249e172ada337be497c0b384ea
