### ISSUE TITLE
As a developer, I can use a custom CA cert to verify SSL connections during builds

### ISSUE THREAD

**Issue by sclevine** [buildpacks/pack#170]
Important for enterprise/corporate users with transparent mitm proxies

**When** I run `pack build --cert /path/to/cert1.pem` --cert /path/to/cert2.pem`
**And** A process in the container reaches out to website using TLS that requires cert1.pem and cert2.pem CA certificates to validate
**Then** The connection succeeds 

**Notes**
- `/etc/ssl/certs`
- Need to run `update-ca-certificates`
- Should we really do this? Poor cross-stack compat

**Comment by ekcasey** [comment]
@sclevine even if we don't prioritize fixing this in the general case (because of the problems with stack portability), we should probably handle the specific case of providing a custom ca for connections to a registry. 

I imagine we could configure that through ggcr and avoid updating the trust store for the entire container.

**Comment by josegonzalez** [comment]
This is something that would be useful in my work - I work on a product that enterprise customers install and require their own random certs to be injected into the container.

One thing I thought of here was to "pre-prepare" a stack based on the generic stack. If I "detected" that I needed to inject files, I would simply to do so before actually calling pack/lifecycle, and then use the resulting image within the build process. I don't like that since it requires keeping track of an intermediate stack outside of the general tooling, but it could be useful if this isn't built into pack/lifecycle.

Semi-related was #169, which thankfully is implemented :)

**Comment by natalieparellano** [comment]
Potentially related to https://github.com/buildpacks/pack/issues/159

**Comment by yonkeltron** [comment]
Hey this is blocking my company's exploration of this technology due to our internal security policies and their expressions as crypto-cracking countermeasures at the edge. Since this is a non-negotiable thing for us, we are unable to proceed much further without this capability. How can we work to resolve this, knowing fully that we're willing to help test this in a corporate environment where Man-In-The-Middle proxies exist in force?

Anything we can do to help would be awesome.

**Comment by zmackie** [comment]
An API for this issue is being discussed in https://github.com/buildpacks/rfcs/pull/69

**Comment by dfreilich** [comment]
There's been recent movement on this (conversation [in slack](https://buildpacks.slack.com/archives/CCP60GJLS/p1593642434382700)) - either to implement it as an experimental flag in pack, or to allow it via a new rfc for `stackpacks` (see more here: https://github.com/buildpacks/rfcs/pull/87)

> in the short term, can we implement a --cert like thing in Pack, even if it's super hacky. Then if the grand(iose) vision of stackpacks works out, the --cert could use it under the hood and we can rm -rf the hack (and it just becomes a convenience feature of the Pack platform)?

cc @nebhale @jkutner

**Comment by jromero** [comment]
Following @dfreilich's update, the alignment during working group was to take the following steps:

1. Research what capabilities are available during buildtime within the docker daemon
2. Start early work on [stack buildpacks](https://github.com/buildpacks/rfcs/pull/87)
3. Possible workaround (within pack) is to use [R/W volume mounts](https://github.com/buildpacks/pack/issues/764)

**Comment by jromero** [comment]
Did a bit of research on this recently. I've cataloged a few [solutions](https://github.com/jromero/buildpacks-ca-certs#solutions) on a separate repo. The lowest hanging solution with reasonable results would be the support the [Read/Write volumes](https://github.com/buildpacks/pack/issues/764) to enable mounting the docker VM certs. It would be analogous to the following command:

```shell
docker run \
    --volume="/etc/ssl/certs:/etc/ssl/certs:ro" \
    --volume="/usr/share/ca-certificates/:/usr/share/ca-certificates/:ro" \
    -it --rm \
    gcr.io/paketo-buildpacks/builder:base \
    /bin/bash
```

**Comment by nebhale** [comment]
Love it!

**Comment by dfreilich** [comment]
@jromero Given that #778 was merged in, can we close this? Or should we keep it open to track in case we need other solutions?

**Comment by nebhale** [comment]
@dfreilich I'd like this left open until I've got a snapshot to test it with.

**Comment by noamichael** [comment]
Any update on this? I've tried mounting the certificate volume but I'm still getting SSL errors when running behind a corporate proxy. Don't we also need to run `update-ca-certificates` after mounting the certificate?

**Comment by jromero** [comment]
@noamichael I can help troubleshoot a little if you want to open a separate issue or reach out via [slack](https://slack.buildpacks.io).

FWIW, `update-ca-certificates` _shouldn't_ be necessary but that would depend on the application. The application can be configured to look solely at `ca-certificates.crt` or the `/etc/ssl/certs/` directory. The former is what gets updated via mount and it's by far the most common.

Here's a [draft post](https://medium.com/@vm_rjavier/using-custom-ca-certs-with-pack-2c2d28230ad1) that has a little more detail. It will likely be moved to buildpacks.io until a more permanent solution is available (such as [stack buildpacks](https://github.com/buildpacks/rfcs/pull/111)).

**Comment by jromero** [comment]
The Paketo buildpacks team have found a buildpack acceptable solution for this. You can find it [here](https://github.com/paketo-buildpacks/ca-certificates). We recommend other providers to do something similar. 

Once [stack buildpacks](https://github.com/buildpacks/rfcs/pull/111) are available additional options for implementation would be available. That said at this point in time this issue has been satisfied.
