### ISSUE TITLE
New rebase option to "retag" rather than replacing the target image

### ISSUE THREAD

**Issue by daniv-msft** [buildpacks/pack#1748]
### Description
When you use `pack rebase` to patch an image, you don't always want to replace it directly in your registry.
It would be great to have an optional parameter on the `rebase` command to retag to something else when rebasing. As of today we need to use Docker directly to clone the target image before rebasing, which isn't great as if anything bad happens during the rebase we'll have a duplicated image in the target registry.

### Proposed solution
Have a new optional `--tag` parameter on the rebase command that allows you to define the new tag to use when rebasing. Alternatively, maybe we can reuse the `--publish` command so that if a full image name with tag is used this value is used?

### Describe alternatives you've considered
Using Docker to perform these operations (not great, cf. above).

### Additional context
- [x] This feature should be documented somewhere

**Comment by dfreilich** [comment]
One open question - In `pack build`, that `-t/--tag` flag is used to specify `additional tags`, in addition to the output image name. Here, would we want `-t/--tag` to specify additional tags, or the only tags released by the command? 

Looking into the technical details, the core of the `rebase` operation is done by the [lifecycle here](https://github.com/buildpacks/lifecycle/blob/main/rebaser.go#L29), and having a different output tag for the rebase operation is sanctioned according to the [spec](https://github.com/buildpacks/spec/blob/main/platform.md#inputs-7). 

Given that, we'd welcome a PR, once we have a resolution about the UX of the tag flag! It should be as simple as:
1. Adding a `Tags []string` array to the [`pkg/client/RebaseOptions`](https://github.com/buildpacks/pack/blob/main/pkg/client/rebase.go#L21)
2. Add a `-t/--tag` flag in the [`internal/commands/rebase.go`](https://github.com/buildpacks/pack/blob/main/internal/commands/rebase.go#L52) definition (changing it to `StringVarP`, so that it can have a `-t` shortform)
3. Pass that tag/tags, if present, to the `lifecycle` in [`pkg/client/rebase.go`](https://github.com/buildpacks/pack/blob/main/pkg/client/rebase.go#L91)
4. Ensure previous tests pass, and add new unit/integration tests (no need for acceptance tests)

**Comment by joeybrown-sf** [comment]
I think this is a reasonable request. In lifecycle, the `-previous-image` flag can be used to accomplish this.

For instance, in the following example we want to rebase the image `foobar:22` but do not want to overwrite the image. Instead, we want to write it to a new tag, `foobar:23`.

The command to accomplish this is as follows:
```
CNB_PLATFORM_API=0.11 lifecycle rebase -previous-image localhost:5003/test/tester/foobar:22 localhost:5003/test/tester/foobar:23
```

I would probably recommend the same flag name for consistency. Pack build also has the [previous-image](https://github.com/buildpacks/pack/blob/8bd4c4902b328186f9817a52b8e0a56e9cd5b5d4/internal/commands/build.go#LL260C1) flag.

**Comment by Parthiba-Hazra** [comment]
Hi @natalieparellano @dfreilich 
if this issue is not been worked yet, can I go for this?

**Comment by natalieparellano** [comment]
@Parthiba-Hazra that would be great! I will assign you

**Comment by Parthiba-Hazra** [comment]
@natalieparellano is there any thing you want share with me before diving on this enhancement, maybe something that can help to get with started? anyway I am going for this.

**Comment by natalieparellano** [comment]
@Parthiba-Hazra apologies for being slow to respond here - I'll discuss with @jjbustamante and one of us should get back early next week

**Comment by Parthiba-Hazra** [comment]
@natalieparellano yes sure, I opened a pr on this one, it does the result. I will need some review on that.

**Comment by jjbustamante** [comment]
Thank you @Parthiba-Hazra 

I will try to take a look on this and review it!
