### ISSUE TITLE
Pack CLI Issue w.r.t vulnerabilities.

### ISSUE THREAD

**Issue by kunaljoshi111** [buildpacks/pack#1821]
We are using Pack CLI for our builder images. However the final application image has a bunch of go binaries under the /cnb folder. These are time and again flagged by our infosec for go related vulnerabilities.

We want to be in a situation where the app built using pack that does NOT have unwanted go libraries? We want to have lean clean images that only contain what is needed to run the app. Example a NodeJS app should run on an image that only has the base OS and NodeJS. Other stuff such as python, go, perl etc are not required and should not be in that image. How can we achieve the same?

**Comment by natalieparellano** [comment]
@kunaljoshi111 it sounds like there are two categories of stuff here - the stuff in /cnb should just be the launcher binary `/cnb/launcher` or symlinks to it. To update the go version in the launcher you would need to re-build the app using the latest lifecycle. We are publishing monthly updates to the lifecycle to ensure that you can always build with the latest go version. 

> Other stuff such as python, go, perl etc are not required and should not be in that image

The presence of this stuff would depend on which buildpacks & base image(s) you are using. You will want to ensure that your base image is as minimal as possible for your app (as an example, if you run `pack builder suggest` you will see that the Paketo project offers 3 classes of builders - base, full, and tiny which would be suitable for different classes of apps). On top of that, the buildpacks should be performing the task of figuring out which dependencies are needed at runtime, and only flagging for export the layers that are necessary. If there are unnecessary dependencies in the app image, either the base image or the buildpacks (or both) would need to be updated to exclude those.

**Comment by jjbustamante** [comment]
Hi @kunaljoshi111

Did you manage to fix your issue? I don't think this is a bug pack and it is more related to documentation on how buildpack ecosystem works. I will close this issue if there is anything else to do on pack side.

**Comment by kunaljoshi111** [comment]
Not really...tried multiple options but none helped.

**Comment by jjbustamante** [comment]
Could help us with some details of which binaries are present under `/cnb/` folder? as Natalie mentioned `/cnb/lifecycle/launcher` or symlinks to it are expected to be there. for example:

![Screenshot 2023-08-14 at 3 04 48 PM](https://github.com/buildpacks/pack/assets/1181799/294b3e39-cacc-473e-972f-e9b4763ac398)

Stuffs at `/home/cnb` or `/layers` or `/workspace` folder depends on the buildpacks you are using, for example, if I build our sample ruby application the output image has the following:

![Screenshot 2023-08-14 at 3 09 08 PM](https://github.com/buildpacks/pack/assets/1181799/8d583302-45fa-43ba-b646-e92df2ed7ecf)

Because we are using a sample ruby buildpacks that is copying several files to the final image we ended up with many files at `/workspace` for example, but if we want to remove that, we need to update our buildpack, that's why we suggest you to take a look at the documentation of your buildpack provider, for example [paketo](https://paketo.io/) to see how you can configure your output image to your particular use case
