### ISSUE TITLE
How to to custom port configuration in buildpack

### ISSUE THREAD

**Issue by tppalani** [buildpacks/pack#2083]
### Description

When we are using dockerfile we can able to add the custom command based on our need. for example let say i want to be install pip, along with this microdnf update, file permission change, entrypoint, Env path, port specification, following items are easily managed using dockerfile, but using pack without dockerfile how we are manage this. please find the below dockerfile.

### Proposed solution

Custom configuration similar to dockerfile

### Additional context
- [ ] This feature should be documented somewhere

```
FROM my-custom-image
USER root

RUN microdnf update -y
RUN ln -sf /usr/bin/python3.11 /usr/bin/python
RUN yum install pip -y
RUN python3.11 -m venv /venv
RUN pip3 install awscli
ENV PATH=/venv/bin:$PATH
ADD requirements.txt requirements.txt
ADD entrypoint.sh ./
RUN dos2unix ./entrypoint.sh
RUN chmod 755 ./entrypoint.sh
ENTRYPOINT ["/bin/sh","entrypoint.sh"]
```

**Comment by dmikusa** [comment]
In a nutshell, they are different tools and part of the point of buildpacks is that you don't need to micro-manage all that stuff. 

For example, with buildpacks...

1. You get a stack/base image set that is kept up-to-date for you so you don't have to constantly run `microdnf update` to keep your images up-to-date.
2. You don't have to install tools like pip/python because the buildpack does this for you
3. You don't have to tweak the PATH because, again, the buildpack sets all this up for you
4. You don't need to set entry points because, again, the buildpacks will do this for you

You provide the source code, and buildpacks turn that into an image. When you do this, it ends up being less work because the repetition is automated away by using buildpacks.

Having said that, there's not a 100% mapping between Dockerfiles and buildpacks. It also depends on what buildpacks you're using, because as you can see it's up to the buildpacks to implement a lot of this.

If you have specific questions about how something works under buildpacks feel free to ask on Slack. Happy to discuss further.

**Comment by jjbustamante** [comment]
Closing this issue because it is not a feature or a bug in `pack`, maybe the gap here is that as a user, is not clear you how to use buildpacks instead of a Dockerfile?

As Daniel said, you can find some guidance on [Paketo](https://paketo.io/) slack, the most important thing I can add is: you can find several buildpacks maintain by the community and the buildpack providers out there that solve many of the common use cases for every application, but, it could be the case where you need to create your own buildpack to satisfy your need, I know it is not trivial to do it, but the community can also help you,  [Paketo](https://paketo.io/) uses some libraries to write their own buildpacks.

Taking one of the things from your exampe Dockerfile, take a look at the [Paketo python buildpack](https://paketo.io/docs/howto/python/) I think they cover several things you mentioned there, what you have to do is use a builder that has python support (Paketo already offers that), but maybe you can also check Heroku or Google builpacks! that's the great thing about the project. 

I hope this can help you! you are free to reach out us in slack too!
