### ISSUE TITLE
Docker Image pack:base does not include shell

### ISSUE THREAD

**Issue by kaiomatico** [buildpacks/pack#2111]
### Summary

Running the command `docker run --rm --it --entrypoint sh buildpacksio/pack:0.33.2-base` works fine, but `docker run --rm --it --entrypoint sh buildpacksio/pack:base` results in the error that sh could not be found in $PATH

---

##### Steps

See above 

##### Current behavior

sh could not be found in $PATH on the base image without version tag 

##### Expected behavior

sh should be included in the base image tag just like it is on the 0.33.2-base image tag

---

##### docker info

Docker 24.0.5 on Linux

**Comment by jjbustamante** [comment]
I think the problem is in this [line](https://github.com/buildpacks/pack/blob/main/.github/workflows/delivery-docker.yml#L76)

We expect to retag the **base, jammy** image to `:base` but we are using an image reference without the `${{ matrix.suffix }}` and we ended up copying the tiny image (based on distroless)

**Comment by natalieparellano** [comment]
@hhiroshell we would love to have your help with this!

For testing stuff out with GitHub Actions (especially jobs that only run after a release) sometimes building out a fork is the only way to do it. But, you might remove the jobs that are irrelevant to what you are testing or require cumbersome setup (see [here](https://github.com/buildpacks/lifecycle/blob/main/tools/test-fork.sh) what we do for the lifecycle including stripping out all tests). Let us know if you run into any issues with it, so that we can unblock you if we can.

**Comment by hhiroshell** [comment]
@natalieparellano Thank you so much for such helpful information. I'll give it a try to do the same!

**Comment by hhiroshell** [comment]
@natalieparellano
I encountered some issues with the `tools/test-fork.sh` script in the lifecycle repository when I tried to run it, so I created a [PR](https://github.com/buildpacks/lifecycle/pull/1384) to fix them. Could you please review it?

**Comment by hhiroshell** [comment]
@natalieparellano
I created a [PR](https://github.com/buildpacks/pack/pull/2235) adding a script for the same purpose as the `tools/test-fork.sh` in the lifecycle repository.

I apologize for the repeated requests, but could you please review it?

**Comment by hhiroshell** [comment]
@natalieparellano 
Thank you for reviewing the series of PRs.

It was also beneficial to study the release process for my understanding.
