### ISSUE TITLE
Enable `pack run` acceptance tests on windows

### ISSUE THREAD

**Issue by jromero** [buildpacks/pack#215]
We currently skip `pack run` acceptance tests on Windows do to the lack of effective clean up. The same clean up procedure works on unix with out issue but for some reason does not on Windows. Running containers, images, etc remain after running that acceptance test.

_Originally posted by @ekcasey in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTc5MjI5Mzk5OnYy/pull_request_review_threads/discussion_

**Comment by dgageot** [comment]
Let my try

**Comment by dgageot** [comment]
I'm not sure I understand what's the issue.

Here's what I see:
 + I don't see where acceptance tests are skipped on Windows
 + Acceptance tests are not run on Travis/Windows. Since Docker is not available, that would anyways not be possible.
 + If I try to run acceptance tests on Windows, there's quite a few errors. Is that what we try to solve?

**Comment by jromero** [comment]
@dgageot Here's a more direct location of where the issue is present:

https://github.com/buildpack/pack/blob/master/acceptance/acceptance_test.go#L614-L617

The repro steps we've used is something like this:

1. In CLI, Run Windows equivalent of `docker rm -f $(docker ps -aq) &>/dev/null; docker system prune --all -f && docker volume prune -f`
2. Run Acceptance Test while marking test mentioned above as `Focus`
3. In CLI, `docker images && docker volume ls && docker ps`

**Notice** there are objects that remain present.

Note: It's been a while since we've tested this so I might have been solved by the Docker daemon on Windows.

> If I try to run acceptance tests on Windows, there's quite a few errors. Is that what we try to solve?

That's alarming. Are the acceptance tests failing in Windows or just seeing errors that could potentially be intentional?

**Comment by dgageot** [comment]
Thanks @jromero for the details. I'm still investigating what's going on. The first issue that I faced is due to https://github.com/buildpack/pack/pull/327. The acceptance tests check the output that is supposed to be free of color codes and this fails.

**Comment by dgageot** [comment]
The next issue I have is with line endings. I need to check if it's caused by my git config.

**Comment by dgageot** [comment]
Ok, the line endings issu is totally due to my git config. Going to look at the cleanup issue now.

**Comment by dgageot** [comment]
Script to clean things up in Powershell
```
docker ps -aq | foreach { docker rm -f $_ }
docker system prune -fa
docker volume prune -f
```

**Comment by dgageot** [comment]
OK, I think I understand what's going on:

+ [this test](https://github.com/buildpack/pack/blob/master/acceptance/acceptance_test.go#L614-L617) interrupts the `pack` command in the middle of its execution.
+ On linux and osx, the `pack` command gets a chance to clean things up before exiting.
+ On windows, this cleanup mechanism doesn't work. So the test leaks volumes and maybe other things.

For what it's worth, [this test](https://github.com/buildpack/pack/blob/master/acceptance/acceptance_test.go#L583), that is not deactivated, also leaks volumes.

Any idea what we should do?

**Comment by dgageot** [comment]
I don't know any way to send a SIGINT signal to a windows process. So that leaves with at least those choices:
 + Run the tests anyways and accept that they will leave uncleaned things behind
 + Add some additional cleaning for those tests, on windows only
 + We add a rudimentary communication mechanism to `pack` for parent processes to signal graceful termination. Could be waiting for a file to be deleted, a named pipe, or something else.

@jromero wdyt?

**Comment by Zanadar** [comment]
@dgageot I think we might want to table this issue since `pack run` is going away anyway (https://github.com/buildpacks/rfcs/pull/36)
