### ISSUE TITLE
Spike/Explore: Running combinatorial tests for PRs

### ISSUE THREAD

**Issue by zmackie** [buildpacks/pack#448]
#### Why are we doing this:
The spike aims to "kill two birds with one stone"
1. Driving our requirements for running pack and/or thelifecycle directly in CI/CD systems
2. Making our PR testing more robust, discoverable, and community friendly.

#### Questions:
- What CI system should we target for the "combinatorial tests"? What parameters can we use to decide which systems we should prioritize? Popularity, container readiness, etc.
- What do we need to do to get it working (changes across pack, etc.)? As in what are the actual requirements?

*Notes*
- If any stories come out of this, create one to update `CONTRIBUTING.md` documentation to include `make acceptance-all`

#### Outputs:
- Concrete actionable issue that PM will help write.

**Comment by Zanadar** [comment]
@ameyer-pivotal I made this into an issue. Feel free to fill out a bit more.

**Comment by natalieparellano** [comment]
Since we recently found that GitHub Actions will allow us to easily obtain a Windows vm with Docker installed, that could be one avenue for solving this problem for Windows. I believe Mac is still an outstanding question.

Other thoughts (captured from a previous conversation awhile back):
* We could move the combinatorial tests to Travis for Linux only
* Use a remote docker daemon for running Mac or Windows
* GitLab lets you have external workers - an alternative to Travis?

**Comment by natalieparellano** [comment]
This has been done in GitHub actions, on Linux only. I believe other OSes are out of scope for now. This issue can probably be closed.

**Comment by jromero** [comment]
Agreed.
