### ISSUE TITLE
pack version should be proper semver

### ISSUE THREAD

**Issue by natalieparellano** [buildpacks/pack#572]
### Description
Today, the version that we use to compile pack is not a proper semver:
```
$  pack version
v0.9.0 (git sha: d42c384a39f367588f2653f2a99702db910e5ad7)
```

### Proposed solution
It should follow the format `0.9.0+build-XXX.sha-asdasdf`

We could start from the work in this PR: https://github.com/buildpacks/pack/pull/396

When running `make build` in GitHub actions, we should compile pack with a meaningful semver if the branch being tested is a release branch. The desired major / minor / patch can be inferred from the branch name. When it's time to cut a release, we can ship the latest artifacts built from automated checks on the release branch.

If the branch being tested is not a release branch, we can compile pack with `0.0.0+build-XXX.sha-asdasdf`.

### Describe alternatives you've considered
Do nothing.

### Additional context
https://semver.org/
> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

### Questions
Do we want to remove the leading `v`? This is removed for now.
Do we need the build number? How do we keep track of it? Using [GITHUB_RUN_NUMBER](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables).
Is this the right format? `0.9.0+build-XXX.sha-asdasdf` See discussion below.
Do we need to warn end-users about this change? (What if there's tooling that parses the output of `pack version`?)

**Comment by jromero** [comment]
Could we possible condense the metadata of the build? This information typically only helps in identifying a specific build and not really intended to be human readable. 

Some suggestions:
```
# positional
0.9.0+{{BUILD#}}.{{GIT_SHA_8}}

# single digit prefix
0.9.0+b{{BUILD#}}.g{{GIT_SHA_8}}
```

**Comment by natalieparellano** [comment]
I dislike prefixing the git sha with a letter because we will inevitably forget and wonder why commits cannot be found. Also I noticed https://github.com/buildpacks/pack/issues/390 mentions using 7 characters from the commit, is there a reason why that changed? I like 7 because that is displayed in various tooling (GitHub, `git lg`).

My suggestion:
`0.9.0+b-{{BUILD#}}.g-{{GIT_SHA_7}}`

**Comment by jromero** [comment]
Looking at the proposed implementation, a few alternatives (in order of preference):

```text
# Format: {{VERSION}}+{{GIT_SHA_7}}.{{BUILD:0}}

# standard example
0.10.0+293db8f.222

# when build is missing default to 0
0.10.0+293db8f.0
```

```text
# Format: {{VERSION}}+{{GIT_SHA_7}}[.{{BUILD}}]

# standard example
0.10.0+git-293db8f.build-222

# when build is missing omit it
0.10.0+git-293db8f
```

What brings me to these suggestions is the following:

1. The git sha should always be available. What is a practical case in which it should be allowed to be missing?
2. I agree with "I dislike prefixing the git sha with a letter because we will inevitably forget and wonder why commits cannot be found". A single letter with a dash (`-`) looks aesthetically awkward in my opinion.
3. Omitting build makes sense but maybe having it default to `0` is more explicit to it being built outside of a standard build system.
4.  git sha should come first as it can be seen as most important and required as mentioned prior.
5. I continue to side with the case that if a positional format is provided, it doesn't have to be explicitly called out inline as to what the information pertains to. As an example, the [lifecycle version](https://github.com/buildpacks/lifecycle/blob/master/cmd/version.go#L29) is printed without the denotation and I would argue that it's sufficient for our purposes.

**Comment by natalieparellano** [comment]
The only time the sha would be missing is if `git rev-parse` fails for some reason. It looks like the lifecycle accounts for the possibility that it could be missing. For this reason I like having labels to avoid confusion in the case that git sha is missing but build is present.

**Comment by jromero** [comment]
I'm okay with that. Thanks for making the changes to the PR.

Sounds like we're in agreeance with:

```
# standard example
0.10.0+git-293db8f.build-222

# when build is missing omit it
0.10.0+git-293db8f

# when git is missing omit it
0.10.0+build-222

# when both missing
0.10.0
```
