### ISSUE TITLE
Pack doesn't honour completely DOCKER_HOST env variable

### ISSUE THREAD

**Issue by jorgemoralespou** [buildpacks/pack#618]
### Summary
Trying to run pack on an education platform we're building that uses Dind (Docker in Docker) running inside Kubernetes pods. 

We have a failure when running `pack` with the java maven quickstart. 

```
echo $DOCKER_HOST
unix:///var/run/docker/docker.sock

pack build myapp --builder cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-builder
...
Digest: sha256:dca51c22ea4226fbbebd47266264448bacfdc10974904815567c6faf7338eb91
Status: Downloaded newer image for cnbs/sample-builder:bionic
bionic: Pulling from cnbs/sample-stack-run
...
Digest: sha256:9c8c9ebdc2cb561664181bb234a9962f9df569394089e5759c72f970db915d89
Status: Downloaded newer image for cnbs/sample-stack-run:bionic
===> DETECTING
[detector] samples/java-maven 0.0.1
===> ANALYZING
[analyzer] ERROR: failed to initialize docker client: failed to connect to docker socket: dial unix /var/run/docker.sock: connect: connection refused
ERROR: failed with status code: 1
``` 

##### Current behavior
As can be seen in the error, it's being reported the docker client trying to connect to `/var/run/docker.sock` while the socket is configured with `DOCKER_HOST=unix:///var/run/docker/docker.sock`

##### Expected behavior
Build should happen ok.

---

##### pack info
```
pack version
0.10.0+git-06d9983.build-259
```

##### docker info
```
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:27:05 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:30:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by natalieparellano** [comment]
@jorgemoralespou thanks for raising this issue. We agree this is something we'd like to fix.

If the referenced connection is a unix socket, the fix seems relatively straightforward - we just need to pass this information through to the lifecycle. If it is a tcp remote connection, we may need to do additional work in case the user supplies a network mode that is not compatible (e.g., `--network none`).

We'll limit the scope for this issue to supporting unix socket hosts, and create another issue to deal with tcp remote connections.

**Comment by jorgemoralespou** [comment]
Thanks, that sounds as it'll work for us, as our platform users Linux socket, but agreed that in the long run it would be worth supporting any option as that's what any regular docker user would expect of a docker tooling.

**Comment by GrahamDumpleton** [comment]
In the end I don't think this is the issue.

On the client side where pack runs it does honour ``DOCKER_HOST``. The actual problem in this case was that it was being run against docker in docker (dind), and in order to share the docker socket from the dind container to the client side container, an emptyDir volume in Kubernetes was used. In order to have the dind side docker.sock in the emptyDir volume, it was necessary to put it somewhere besides ``/var/run/docker.sock``.

Thus the issue was that the analyser is trying to mount ``/var/run/docker.sock`` into the container it is running (on dind side), but it wasn't at the expected location and ended up mounting an empty directory into the analyser container instead.

The fix for the issue is when starting up the dind container, to create a symlink at ``/var/run/docker.sock`` which points at the actual location of the socket in the emptyDir volume. With that done the analyser seems to be able to mount the docker socket okay and things work.

Will do further checks but I believe this issue can be closed as it outside of your control. It is probably an unwritten role that on the docker host (dind in this case), the docker socket must be at ``/var/run/docker.sock`` and there is no way it can be anywhere else as too much relies on it.

**Comment by jorgemoralespou** [comment]
I'm going to close this issue since from our triage doesn't really match the description and it's a corner case of how we run pack inside kubernetes pods.
