### ISSUE TITLE
homebrew-tap upgrade was generated with incorrect artifacts

### ISSUE THREAD

**Issue by ekcasey** [buildpacks/pack#859]
### Summary
Homebrew tap release automation generated a broken formula:

https://github.com/buildpacks/homebrew-tap/pull/14

**Comment by jromero** [comment]
### Summary
As a homebrew user, I am unable to install or upgrade to the latest version of pack.

---

### Reproduction

**NOTE: @ekcasey has manually update the formula.**



##### Steps

1. `brew install buildpacks/tap/pack`

OR

1. `brew upgrade pack`

##### Current behavior

<img width="1432" alt="Image from iOS" src="https://user-images.githubusercontent.com/475559/94825021-47a25f00-03cb-11eb-8ca2-0637a5080b76.png">


The file being distributed is the new checksum file: https://github.com/buildpacks/homebrew-tap/commit/a56edff76cc2c161170a4aa927faa19bb5ffdc00

##### Expected behavior


The file distributed should be the `tgz` file.

---

### Environment

N/A
