### ISSUE TITLE
Add -gid Flag to Pack to Support OpenShift

### ISSUE THREAD

**Issue by noamichael** [buildpacks/pack#961]
### Description

In OpenShift, [the default security rules dictate that images are able to run as a random user](https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#use-uid). Many organizations have this rule strictly enforced.

RedHat's recommended approach to granting user read/write/execute permissions is to grant group `0` those permissions instead because the random user is guaranteed to be in that group.

```bash
RUN chgrp -R 0 /some/directory && \
    chmod -R g+rwX /some/directory
```

In order to support this, Buildpack stack run images must set the `CNB_GROUP_ID` to `0`.

### Proposed solution

Since having to customize every stack that needs to run in OpenShift is a lot of work, it would probably be better to add a `-gid` flag to `pack` in order to allow the group to be overridden specifically at build time.

**Comment by e1m1** [comment]
This would be very useful!

**Comment by jromero** [comment]
I have a few concerns about this that we'd probably want to address before implementing:

1. It is my understanding that `-gid` and `CNB_GROUP_ID` should match. I would like to get a better understanding of the implications if they don't. Should the lifecycle override the `CNB_GROUP_ID` env var when `-gid` is provided?
2. If the need is solely to be able to set it to `0` for compatibility to with OpenShift then should this request actually be made to the stack providers (paketo, heroku, google, etc) and there be some recommendation in our docs?
3. This option added only to pack seem fairly limited to the ecosystem. There are various integrations with CNBs. Only having the option to do this within pack doesn't seem ideal. A way to improve this may be to add it to the [project descriptor spec](https://github.com/buildpacks/spec/blob/main/extensions/project-descriptor.md) so that the configuration for the project is at least portable to integrations that implement that extension.

CC: @ekcasey

**Comment by jromero** [comment]
For context, a relevant slack conversation: https://buildpacks.slack.com/archives/C94UJCNV6/p1605623879266600

**Comment by jromero** [comment]
> 1. It is my understanding that -gid and `CNB_GROUP_ID` should match. I would like to get a better understanding of the implications if they don't. Should the lifecycle override the `CNB_GROUP_ID` env var when -gid is provided?

The `CNB_GROUP_ID` env var is _solely_ used to provide configuration to the lifecycle and in this case is overwritten by `-gid` which makes it a safe operation. There are no foreseen complications with this approach.

**Comment by jromero** [comment]
Based on the answer above, I would suggest that we move forward with the implementation of providing a `--gid` flag to `pack`. We can start discussions about points #2 and #3 in the working group meetings or per RFCs but they shouldn't be blockers for this particular issue.

**Comment by jromero** [comment]
### Acceptance Criteria

```gherkin
Given there is a builder "X"
And builder "X" has "CNB_GROUP_ID = 1000"
And builder "X" has "USER 1000:1000"
When the user executes "pack build my-app -B X --gid 0"
Then the build should succeed
And the owning group should be `0` of the contents in "/workspace/" within the app image
```

**Comment by sampeinado** [comment]
Hey @noamichael! I am working on getting some feedback from users about the buildpacks UX and what's important. Would you be up for a 60-90 min interview this week or next so that I can learn more from your experience? We would compensate $250 for your time!

**Comment by dfreilich** [comment]
One additional Acceptance Criteria: we should also add it to `pack rebase`, and thread it to down to the lifecycle using the `--gid` flag ([here](https://github.com/buildpacks/spec/blob/main/platform.md#rebaser))

**Comment by ekcasey** [comment]
@dfreilich since pack uses the lifecycle as a library during `rebase` it isn't relevant. The `rebaser` executable only accepts `-gid` so it can do things as root, like connect to the daemon, and then drop privileges. If you are running the rebase logic in the pack process this is unnecessary.
